### ISSUE TITLE
Google Play Protect warnings

### ISSUE THREAD

**Issue by ineffyble** [joaomgcd/TaskerSettings#17]
When I tried to install the app from the Play Store I wasn't able to, as I was told the app needed to be updated to work on my device.

When I tried to install the 1.5.0 APK downloaded from the GitHub release I was shown a Play Protect warning that the app was harmful, and I had to choose the "install anyway" option. But since installing I've started receiving notifications from Play Protect telling me I have a harmful app I should remove:

![Screenshot_20230429_212137_Google Play Store](https://user-images.githubusercontent.com/834880/235300069-ece9b5c9-00f3-479d-b561-213d6a1f24d8.jpg)

I am assuming this is expected but I couldn't find any previous users who've encountered this, so I wanted to confirm.

Device is a Samsung Galaxy Z Fold2 running Android 13.

**Comment by pascallj** [comment]
Same issue here on a Pixel 6a running Android 13. Just installed the latest version because the icon did not match with the new version of Tasker (and the launcher won't hide the app) and Google Play Protect has prompted me a couple of times already.

This might be a result of Google's attempt to restrict access to old API versions which is gonna be introduced in Android 14. However I didn't have any problems with version 1.2.0 which is also targeted at an old API version.
