### ISSUE TITLE
Kaspersky AV finds trojan in the latest release

### ISSUE THREAD

**Issue by CaesarRulezzz** [joaomgcd/TaskerSettings#33]
HEUR:Trojan.AndroidOS.Boogr.gsh

**Comment by joaomgcd** [comment]
Yes. Other people reported it as well. Unfortunately I don't control how anti-virus programs work so all I can say is that it's a false positive maybe caused by all the permissions Tasker requests? I can't really know for sure. All I can ask is if you can report the false-positive here: https://forum.kaspersky.com/topic/kaspersky-how-to-report-false-positive-22328/
That would probably help!

Thanks in advance!
