### ISSUE TITLE
Tasker.Settings.1.6.0.apk reports a virus in MS Defender

### ISSUE THREAD

**Issue by c11umw** [joaomgcd/TaskerSettings#41]
Tried to download the APK Tasker.Settings.1.6.0 [from here](https://github.com/joaomgcd/TaskerSettings/releases/tag/v.1.6.0), but chrome deleted it reporting a virus
![image](https://github.com/joaomgcd/TaskerSettings/assets/48920056/740943ca-5f80-4ac3-9694-1d44c3ad2bf3)

Firefox could download, but as soon as I tried to ADB it to my tablet it would be removed.
Did a Defender check on it and it reports a virus in the code: Trojan:AndroidOS/Multiverze

![image](https://github.com/joaomgcd/TaskerSettings/assets/48920056/d71d6ee9-c6ea-4d51-9da1-7971d90b4622)

Not sure if that's a false alert or not, but thought you should know in case you need to pull that release or re-compile to get around the alert.

**Comment by joaomgcd** [comment]
Unfortunately I can't control what Anti-virus apps report as viruses, sorry :( All I can say is that the app is open source and you can check the code to see exactly what it does. Sorry!

A re-compile wouldn't help because the code would still be the same and also be flagged as a virus for some reason.

thanks for the suggestion though!

**Comment by honggiwei** [comment]
It's not virus.
It is only not verified by official web site.
I have doubled scanned it by many online scan tool. It show no virus.

MS defender only want to show : this app is "grey aera code".

Installation of apps from unknown or unverified download sites

https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3AAndroidOS%2FMultiverze&threatid=2147785333
